# Generated by Django 6.0.3 on 2026-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/blog_default.jpg', upload_to='blog_images/'),
        ),
    ]
