# Generated by Django 6.0.3 on 2026-03-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
